### ISSUE TITLE
Feature request: .npmpostintallrc

### ISSUE THREAD

**Issue by coleturner** [kapouer/postinstall-links#4]
Hey! Love this idea and wanted this kind of solution for my own use.

I would suggest implementing a .nmplinkrc file that can be ignored by git since teams might be working on different features or dependencies. This would allow npm links to be distinct between contributors while the git repository remains agnostic. Or it could be checked in if that's the desire.

Cheers!

**Comment by kapouer** [comment]
I don't understand your suggestion, could you be more explicit, please ?

**Comment by coleturner** [comment]
Similar to how you have it in `package.json` I am suggesting to add a new file that can be optionally checked into the repository:

`.npmlinkrc`

Contents:
```json
{
   "links": {
       "jquery/dist/jquery.slim.min.js": "public/",
       "jquery/dist/jquery.js": "public/jquery.dev.js",
       "flickity/dist/*": "public/flickity/"
   }
}
```

This would allow developers on teams to have different links (for example when we're building specific features)

**Comment by kapouer** [comment]
Understood.
I guess that file should be searched into the same dir as package.json,
and better be in a simple format (lines matching `^(.+)\s+(.+)$`)
```
jquery/dist/jquery.slim.min.js               public/
flickity/dist/*                              public/flickity/
```

**Comment by coleturner** [comment]
That works too, although a JSON file would allow you to extend more optional configuration in the future. If time is an issue I'm happy to contribute a PR this weekend.

Cheers!

**Comment by kapouer** [comment]
Then an ini file format would be better.
I'm not fond of json for configuration formats... and a PR will be welcome !

**Comment by kapouer** [comment]
I'd try to generalize a little the idea of a "postinstall configuration file":
- name it .npmpostinstallrc
- use a `[links]` section (ini syntax)

that way if anyone comes up with a `postinstall-browserify` package, the way will be paved for a `[browserify]` section.

**Comment by kapouer** [comment]
FYI i'm (slowly, don't hold your breath) preparing a release of `postinstall` that would go with plugins (like `postintall-links`).

**Comment by kapouer** [comment]
You can try [postinstall](https://github.com/kapouer/postinstall) module now.
The syntax has changed a little, check the README.
Besides the bundled commands, [postinstall-js](https://github.com/kapouer/postinstall-js) and [postinstall-css](https://github.com/kapouer/postinstall-css) will do wonders.
